__default__:
  mem: "4G"
  cpus: "1"
  name: "JOBNAME.{rule}.{wildcards}"
  output: "logs/{rule}.{wildcards}.out"
  time: "4:00:00"

map:
  cpus: "4"
  mem: "15G"
  time: "2-0:00:00"

merge_readgroups:
  cpus: "2"

mark_duplicates:
  mem: "8G"
  time: "8:00:00"

merge_libraries:
  cpus: "2"
  mem: "5G"

bam2bed:
  time: "1:00:00"

blacklist_filter:
  mem: "100M"
  time: "10:00"

merge_master_peaks:
  mem: "100M"
  time: "10:00"

versions:
  mem: "100M"
