__default__:
    mem: 6000
    cpus: 1
    name: JOBNAME.{rule}.{wildcards}
    output: logs/{rule}.{wildcards}.out
    time: 10:00:00

map:
    cpus: 4
    mem: 15000

mark_duplicates:
    mem: 15000

merge:
    mem: 5000

prune:
    mem: 4000

trim:
    mem: 5000

versions:
    mem: 500
